#!/bin/bash

rm -rf package
rm package.zip
pip install --target ./package -r requirements.txt
cd package
zip -r ../package.zip .
cd ..
zip -g package.zip lambda_function.py
aws lambda update-function-code --function-name wwf-notification --zip-file fileb://package.zip --region eu-central-1
